services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-salus}

    volumes:
      - postgres-db-volume:/var/lib/postgresql

    ports:
      - "5432:5432"

  salus-api:
    image: salus-api
    restart: unless-stopped
    ports: 
      - 8080:8080
    volumes:
      - /var/media/salus/uploads:/app/uploads
    depends_on:
      - postgres

  salus-frontend:
    image: salus-frontend
    restart: unless-stopped
    ports: 
      - 3000:3000

volumes:
  postgres-db-volume:   

networks:
  default:
    driver: bridge
